export const FETCH_EVENTS_START = 'FETCH_EVENTS_START';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILED = 'FETCH_EVENTS_FAILED';

export const FETCH_ONE_EVENTS_START = 'FETCH_ONE_EVENTS_START';
export const FETCH_ONE_EVENTS_SUCCESS = 'FETCH_ONE_EVENTS_SUCCESS';
export const FETCH_ONE_EVENTS_FAILED = 'FETCH_ONE_EVENTS_FAILED';