export const FETCH_MYFUND_START = 'FETCH_MYFUND_START';
export const FETCH_MYFUND_SUCCESS = 'FETCH_MYFUND_SUCCESS';
export const FETCH_MYFUND_FAILED = 'FETCH_MYFUND_FAILED';

export const NEW_MYFUND_START = 'NEW_MYFUND_START';
export const NEW_MYFUND_SUCCESS = 'NEW_MYFUND_SUCCESS';
export const NEW_MYFUND_FAILED = 'NEW_MYFUND_FAILED';